
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='eventz',
    version='0.3.0',
    description='Eventz: an event-centric microframework.',
    python_requires='==3.*,>=3.8.0',
    author='Dan Ballance',
    author_email='work@danballance.uk',
    packages=['eventz'],
    package_dir={"": "."},
    package_data={},
    install_requires=['immutables==0.*,>=0.14.0', 'python-dateutil==2.*,>=2.8.1'],
    extras_require={"dev": ["pytest==5.*,>=5.2.0", "pytest-cov==2.*,>=2.10.0"]},
)
